require "user.options"
require "user.plugins"
require "user.keybinds"
require "user.colorscheme"
require "user.lsp"
require "user.treesitter"
require "user.cmp"
-- require "user.telescope"
require "user.oil"
require "user.fzf"
-- require "user.neotest"
require "user.vim-test"
require "user.toggleterm"
require "user.comment"
require "user.trouble"
require "user.copilot"
require "user.osc52"
require "user.nvim-web-devicons"
require "user.lualine"
